const COMPLETED_RESERVATIONS_SELECTOR_MANAGEMENT_RESERVATIONS  = "#completedReservations tbody";
const COMPLETED_RESERVATIONS_SELECTOR_CONFLICTS  = "#resolvedConflicts tbody";
const ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB  = "#active-reservations-tab";
const ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB_CONFLICTS  = "#active-conflicts-tab";

const ACTIVE_RESERVATIONS_TBODY = "#activeReservations tbody";
const ACTIVE_CONFLICTS_TBODY = "#activeConflicts tbody"






export {COMPLETED_RESERVATIONS_SELECTOR_MANAGEMENT_RESERVATIONS, COMPLETED_RESERVATIONS_SELECTOR_CONFLICTS, ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB, ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB_CONFLICTS, ACTIVE_RESERVATIONS_TBODY, ACTIVE_CONFLICTS_TBODY}
