const COMPLETED_RESERVATIONS_SELECTOR_MANAGEMENT_RESERVATIONS  = "#completedReservations tbody";
const COMPLETED_RESERVATIONS_SELECTOR_CONFLICTS  = "#completedReservations tbody2";
const ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB  = "#active-reservations-tab";
const ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB_CONFLICTS  = "#active-reservations-tab-2";








export {COMPLETED_RESERVATIONS_SELECTOR_MANAGEMENT_RESERVATIONS, COMPLETED_RESERVATIONS_SELECTOR_CONFLICTS, ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB, ARIA_LABELLED_BY_ACTIVE_RESERVATIONS_TAB_CONFLICTS}
